version: "3"

services:
  db:
    image: mariadb:10
    ports:
      - 3307:3307
    restart: always
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    environment:
      TZ: Asia/Seoul
      MYSQL_TCP_PORT: 3307
      MYSQL_UNIX_PORT: 3307
    networks:
      - backend
    restart: always

networks:
  backend: